runtime: nodejs14

instance_class: F2

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6

handlers:
  - url: /.*
    script: auto

